[workspace]
resolver = "2"
members = [
    "crates/miui-core",
    "crates/miui-macos",
    "crates/miui-web",
    "crates/miui-windows",
    "crates/miui-gtk",
    "crates/miui",
    "examples/counter",
    "examples/gallery",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mokuichi147/miui"

[workspace.dependencies]
miui-core = { path = "crates/miui-core", version = "0.2.0" }
miui-macos = { path = "crates/miui-macos", version = "0.2.0" }
miui-web = { path = "crates/miui-web", version = "0.2.0" }
miui-windows = { path = "crates/miui-windows", version = "0.2.0" }
miui-gtk = { path = "crates/miui-gtk", version = "0.2.0" }
miui = { path = "crates/miui", version = "0.2.0" }

[profile.release]
opt-level = 3
lto = "thin"
strip = true
