[workspace]
resolver = "2"
members = [
    "crates/naui-core",
    "crates/naui-macos",
    "crates/naui-web",
    "crates/naui-windows",
    "crates/naui-winui3",
    "crates/naui-gtk",
    "crates/naui",
    "examples/counter",
    "examples/gallery",
]
exclude = ["tools/winui3-bindgen"]

[workspace.package]
version = "0.4.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mokuichi147/naui"

[workspace.dependencies]
naui-core = { path = "crates/naui-core", version = "0.4.0" }
naui-macos = { path = "crates/naui-macos", version = "0.4.0" }
naui-web = { path = "crates/naui-web", version = "0.4.0" }
naui-windows = { path = "crates/naui-windows", version = "0.4.0" }
naui-winui3 = { path = "crates/naui-winui3", version = "0.4.0" }
naui-gtk = { path = "crates/naui-gtk", version = "0.4.0" }
naui = { path = "crates/naui", version = "0.4.0" }

[profile.release]
opt-level = 3
lto = "thin"
strip = true
