[package]
name = "gallery"
description = "naui の全ウィジェットのデモ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "gallery"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "gallery"
path = "src/main.rs"

[dependencies]
naui.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
